import { GameProviderFolderMapping, ProcessedGameData } from './types';

export const APP_TITLE = "Hard Rock MX Game Creator";

export const GAME_PROVIDER_TO_FOLDER_MAP_CA: GameProviderFolderMapping = {
  "AGS": "AGS",
  "Greentube": "Green Tube",
  "Pragmatic": "Pragmatic",
  "Games Global": "games-global",
  "Hacksaw": "Hacksaw",
  "HACKSAW OpenRGS": "Hacksaw",
  "HACKSAW": "Hacksaw", // Added for all-caps input
  "ELK-Studios": "ELK-Studios",
  "ELK Studios via LNW": "ELK-Studios",
  "ELK Studios": "ELK-Studios",
  "Gaming Realms": "Gaming Realms",
  "High 5": "High 5",
  "High5 via SG": "High 5",
  "Lightning Box": "Lightning Box",
  "Peter & Sons": "Peter & Sons",
  "Quickspin": "Quickspin",
  "SG": "SG",
  "Wazdan": "Wazdan",
  "Blueprint": "Blueprint",
  "Bragg": "Bragg",
  "eyecon": "eyecon",
  "Eyecon": "eyecon", // Added for case-insensitivity
  "IGT": "IGT",
  "Konami": "Konami",
  "Konami via SG": "Konami",
  "Inspired": "Inspired",
  "Live Casino": "Live Casino",
  "Oryx": "Oryx",
  "Playtech": "Playtech",
  "Relax Gaming": "Relax Gaming",
  "SkyWind": "SkyWind",
  "Skywind": "SkyWind", // Ensure consistent folder casing
  "Drops & Wins": "Drops & Wins",
  "RubyPlay": "Rubyplay", // Custom folder name for CA export
  "Test": "Test" // Added based on COM screenshot
};

export const GAME_PROVIDER_TO_FOLDER_MAP_COM: GameProviderFolderMapping = {
  // From screenshot - these take precedence
  "Blueprint": "Blueprint",
  "Bragg": "Bragg",
  "Drops & Wins": "Drops & Wins",
  "Games Global": "Games Global", // Screenshot: "Games Global" (CA: "games-global")
  "Live Casino": "Live Casino",
  "Oryx": "Oryx",
  "Peter & Sons": "Peter & Sons",
  "Playtech": "Playtech",
  "Pragmatic": "Pragmatic",
  "Quickspin": "Quickspin",
  "RubyPlay": "RubyPlay",
  "Test": "Test",

  // Providers from CA map NOT in screenshot - maintain consistency or use direct name
  "AGS": "AGS",
  "Greentube": "Greentube", // CA was "Green Tube", using direct name for COM
  "Hacksaw": "Hacksaw",
  "HACKSAW OpenRGS": "Hacksaw",
  "HACKSAW": "Hacksaw", // Added for all-caps input
  "ELK-Studios": "ELK-Studios",
  "ELK Studios via LNW": "ELK-Studios",
  "ELK Studios": "ELK-Studios",
  "Gaming Realms": "Gaming Realms",
  "High 5": "High 5",
  "High5 via SG": "High 5",
  "Lightning Box": "Lightning Box",
  "SG": "SG",
  "Wazdan": "Wazdan",
  "eyecon": "eyecon",
  "Eyecon": "eyecon", // Added for case-insensitivity
  "IGT": "IGT",
  "Konami": "Konami",
  "Konami via SG": "Konami",
  "Inspired": "Inspired",
  "Relax Gaming": "Relax Gaming",
  "SkyWind": "SkyWind",
  "Skywind": "SkyWind", // Ensure consistent folder casing
};


// Mappings for the ORIGINAL input format
export const INPUT_HEADER_MAPPINGS = {
  NAME: "Name",
  GAME_PROVIDER: "Game Provider",
  PROVIDER_GAME_CODE: "Provider Game Code",
  IMS_GAME_CODE: "IMS Game Code",
  CATEGORY: "Category",
  TILE_STATUS: "Tile", // Landscape tile status from screenshot
  PORTRAIT_TILE_STATUS: "Portrait Tile",
} as const;

export const CORE_REQUIRED_INPUT_HEADER_KEYS: (keyof typeof INPUT_HEADER_MAPPINGS)[] = [
  'NAME',
  'GAME_PROVIDER',
  'IMS_GAME_CODE',
];

export const PLACEHOLDER_INFO_REQUIRED_COLUMNS = "Core required headers: Name, Game Provider, IMS Game Code.";

// Columns for the NEW output CSV format
export const OUTPUT_CSV_COLUMNS: (keyof ProcessedGameData | string)[] = [
  'gameCode',
  'name',
  'isActive',
  'mobileGameCode',
  'seoFriendlyGameName',
  'desktopGameType',
  'mobileGameType',
  'liveLaunchAlias',
  'bingoGameType',
  'vfGameType',
  'jackpotCode',
  'demoModeSupport',
  'gameMode',
  'gameProvider',
  'urlCustomParameters',
  'isExcludedFromPGG',
  'isExcludedFromSitemap',
  'deviceAvailability_mobile',
  'deviceAvailability_tablet',
  'deviceAvailability_desktop',
  'browserAvailability_edge',
  'browserAvailability_safari',
  'browserAvailability_chrome',
  'browserAvailability_firefox',
  'browserAvailability_other',
  'osAvailability_ios',
  'osAvailability_macintosh',
  'osAvailability_android',
  'osAvailability_windows',
  'osAvailability_other',
  'defaultGameImage',
  'landscape_layout1x1_mainImage',
  'landscape_layout1x1_mobileImage',
  'landscape_layout1x1_guestMainImage',
  'landscape_layout1x1_guestMobileImage',
  'landscape_layout1x2_mainImage',
  'landscape_layout1x2_mobileImage',
  'landscape_layout1x2_guestMainImage',
  'landscape_layout1x2_guestMobileImage',
  'landscape_layout2x1_mainImage',
  'landscape_layout2x1_mobileImage',
  'landscape_layout2x1_guestMainImage',
  'landscape_layout2x1_guestMobileImage',
  'landscape_layout2x2_mainImage',
  'landscape_layout2x2_mobileImage',
  'landscape_layout2x2_guestMainImage',
  'landscape_layout2x2_guestMobileImage',
  'square_layout1x1_mainImage',
  'square_layout1x1_mobileImage',
  'square_layout1x1_guestMainImage',
  'square_layout1x1_guestMobileImage',
  'square_layout1x2_mainImage',
  'square_layout1x2_mobileImage',
  'square_layout1x2_guestMainImage',
  'square_layout1x2_guestMobileImage',
  'square_layout2x1_mainImage',
  'square_layout2x1_mobileImage',
  'square_layout2x1_guestMainImage',
  'square_layout2x1_guestMobileImage',
  'square_layout2x2_mainImage',
  'square_layout2x2_mobileImage',
  'square_layout2x2_guestMainImage',
  'square_layout2x2_guestMobileImage',
  'portrait_layout1x1_mainImage',
  'portrait_layout1x1_mobileImage',
  'portrait_layout1x1_guestMainImage',
  'portrait_layout1x1_guestMobileImage',
  'portrait_layout1x2_mainImage',
  'portrait_layout1x2_mobileImage',
  'portrait_layout1x2_guestMainImage',
  'portrait_layout1x2_guestMobileImage',
  'portrait_layout2x1_mainImage',
  'portrait_layout2x1_mobileImage',
  'portrait_layout2x1_guestMainImage',
  'portrait_layout2x1_guestMobileImage',
  'portrait_layout2x2_mainImage',
  'portrait_layout2x2_mobileImage',
  'portrait_layout2x2_guestMainImage',
  'portrait_layout2x2_guestMobileImage',
  'articleId',
  'mobileArticleId',
  'description',
  'isGameNew',
  'isGamePopular',
  'isGameHot',
  'isGameExclusive',
  'gameLabelsData_Exclusive',
  'gameLabelsData_New',
  'gamesCustomFields_gameType',
  'gamesCustomFields_Theme',
  'gamesCustomFields_features',
  'gamesCustomFields_volatility',
  'gamesCustomFields_rtp',
  'gamesCustomFields_Paylines',
  'gamesCustomFields_reels',
  'gamesCustomFields_provider',
  'rtp',
  'volatilityIndex',
  'isFreeSpinsFeatureActive',
  'isGoldenChipsFeatureActive',
  'gameLabelsData_Best',
  'gameLabelsData_Exclusive',
  'gameLabelsData_Hot',
  'gameLabelsData_New',
  'gamesCustomFields_Screenshot',
  'gamesCustomFields_Min bet',
  'gamesCustomFields_Description',
];