
import { GameProviderFolderMapping, ProcessedGameData } from './types';

export const APP_TITLE = "Portal Game CSV Generator";

export const GAME_PROVIDER_TO_FOLDER_MAP_CA: GameProviderFolderMapping = {
  "AGS": "AGS",
  "Greentube": "Green Tube",
  "Pragmatic": "Pragmatic",
  "Games Global": "games-global",
  "Hacksaw": "Hacksaw",
  "HACKSAW OpenRGS": "Hacksaw",
  "HACKSAW": "Hacksaw", // Added for all-caps input
  "ELK-Studios": "ELK-Studios",
  "ELK Studios via LNW": "ELK-Studios",
  "ELK Studios": "ELK-Studios",
  "Gaming Realms": "Gaming Realms",
  "High 5": "High 5",
  "High5 via SG": "High 5",
  "Lightning Box": "Lightning Box",
  "Peter & Sons": "Peter & Sons",
  "Quickspin": "Quickspin",
  "SG": "SG",
  "Wazdan": "Wazdan",
  "Blueprint": "Blueprint",
  "Bragg": "Bragg",
  "eyecon": "eyecon",
  "Eyecon": "eyecon", // Added for case-insensitivity
  "IGT": "IGT",
  "Konami": "Konami",
  "Konami via SG": "Konami",
  "Inspired": "Inspired",
  "Live Casino": "Live Casino",
  "Oryx": "Oryx",
  "Playtech": "Playtech",
  "Relax Gaming": "Relax Gaming",
  "SkyWind": "SkyWind",
  "Skywind": "SkyWind", // Ensure consistent folder casing
  "Drops & Wins": "Drops & Wins",
  "RubyPlay": "Rubyplay", // Custom folder name for CA export
  "Test": "Test" // Added based on COM screenshot
};

export const GAME_PROVIDER_TO_FOLDER_MAP_COM: GameProviderFolderMapping = {
  // From screenshot - these take precedence
  "Blueprint": "Blueprint",
  "Bragg": "Bragg",
  "Drops & Wins": "Drops & Wins",
  "Games Global": "Games Global", // Screenshot: "Games Global" (CA: "games-global")
  "Live Casino": "Live Casino",
  "Oryx": "Oryx",
  "Peter & Sons": "Peter & Sons",
  "Playtech": "Playtech",
  "Pragmatic": "Pragmatic",
  "Quickspin": "Quickspin",
  "RubyPlay": "RubyPlay",
  "Test": "Test",

  // Providers from CA map NOT in screenshot - maintain consistency or use direct name
  "AGS": "AGS",
  "Greentube": "Greentube", // CA was "Green Tube", using direct name for COM
  "Hacksaw": "Hacksaw",
  "HACKSAW OpenRGS": "Hacksaw",
  "HACKSAW": "Hacksaw", // Added for all-caps input
  "ELK-Studios": "ELK-Studios",
  "ELK Studios via LNW": "ELK-Studios",
  "ELK Studios": "ELK-Studios",
  "Gaming Realms": "Gaming Realms",
  "High 5": "High 5",
  "High5 via SG": "High 5",
  "Lightning Box": "Lightning Box",
  "SG": "SG",
  "Wazdan": "Wazdan",
  "eyecon": "eyecon",
  "Eyecon": "eyecon", // Added for case-insensitivity
  "IGT": "IGT",
  "Konami": "Konami",
  "Konami via SG": "Konami",
  "Inspired": "Inspired",
  "Relax Gaming": "Relax Gaming",
  "SkyWind": "SkyWind",
  "Skywind": "SkyWind", // Ensure consistent folder casing
};


export const INPUT_HEADER_MAPPINGS = {
  GAME_CODE: "IMS Game Code",
  NAME: "Name",
  IS_ACTIVE: "isActive",
  MOBILE_GAME_CODE: "mobileGameCode",
  SEO_FRIENDLY_GAME_NAME: "seoFriendlyGameName",
  DESKTOP_GAME_TYPE: "desktopGameType",
  MOBILE_GAME_TYPE: "mobileGameType",
  LIVE_LAUNCH_ALIAS: "liveLaunchAlias",
  BINGO_GAME_TYPE: "bingoGameType",
  RTP_GAME_TYPE: "rtpGameType",
  JACKPOT_CODE: "jackpotCode",
  DEMO_MODE_SUPPORT: "defaultSlotModeSupport",
  GAME_MODE: "gameMode",
  GAME_PROVIDER: "Game Provider",
  URL_CUSTOM_PARAMETERS: "urlCustomParameters",
  IS_EXCLUDED_FROM_PGG: "isExcludedFromRGS",
  IS_EXCLUDED_FROM_SITEMAP: "isExcludedFromSitemap",
  DEVICE_AVAILABILITY_MOBILE: "deviceAvailability_mobile",
  DEVICE_AVAILABILITY_TABLET: "deviceAvailability_tablet",
  DEVICE_AVAILABILITY_DESKTOP: "deviceAvailability_desktop",
  BROWSER_AVAILABILITY_EDGE: "browserAvailability_edge",
  BROWSER_AVAILABILITY_SAFARI: "browserAvailability_safari",
  BROWSER_AVAILABILITY_CHROME: "browserAvailability_chrome",
  BROWSER_AVAILABILITY_FIREFOX: "browserAvailability_firefox",
  BROWSER_AVAILABILITY_OTHER: "browserAvailability_other",
  OS_AVAILABILITY_IOS: "osAvailability_ios",
  OS_AVAILABILITY_MACINTOSH: "osAvailability_macintosh",
  OS_AVAILABILITY_ANDROID: "osAvailability_android",
  OS_AVAILABILITY_WINDOWS: "osAvailability_windows",
  OS_AVAILABILITY_OTHER: "osAvailability_other",
  DEFAULT_USER_IMAGE: "defaultUserImage",

  LANDSCAPE_LAYOUT_1X1_MAIN_IMAGE: "landscape_layout1x1_mainImage",
  LANDSCAPE_LAYOUT_1X1_MOBILE_IMAGE: "landscape_layout1x1_mobileImage",
  LANDSCAPE_LAYOUT_1X1_GUEST_MAIN_IMAGE: "landscape_layout1x1_guestMainImage",
  LANDSCAPE_LAYOUT_1X1_GUEST_MOBILE_IMAGE: "landscape_layout1x1_guestMobileImage",
  LANDSCAPE_LAYOUT_1X2_MAIN_IMAGE: "landscape_layout1x2_mainImage",
  LANDSCAPE_LAYOUT_1X2_MOBILE_IMAGE: "landscape_layout1x2_mobileImage",
  LANDSCAPE_LAYOUT_1X2_GUEST_MAIN_IMAGE: "landscape_layout1x2_guestMainImage",
  LANDSCAPE_LAYOUT_1X2_GUEST_MOBILE_IMAGE: "landscape_layout1x2_guestMobileImage",
  LANDSCAPE_LAYOUT_2X1_MAIN_IMAGE: "landscape_layout2x1_mainImage",
  LANDSCAPE_LAYOUT_2X1_MOBILE_IMAGE: "landscape_layout2x1_mobileImage",
  LANDSCAPE_LAYOUT_2X1_GUEST_MAIN_IMAGE: "landscape_layout2x1_guestMainImage",
  LANDSCAPE_LAYOUT_2X1_GUEST_MOBILE_IMAGE: "landscape_layout2x1_guestMobileImage",
  LANDSCAPE_LAYOUT_2X2_MAIN_IMAGE: "landscape_layout2x2_mainImage",
  LANDSCAPE_LAYOUT_2X2_MOBILE_IMAGE: "landscape_layout2x2_mobileImage",
  LANDSCAPE_LAYOUT_2X2_GUEST_MAIN_IMAGE: "landscape_layout2x2_guestMainImage",
  LANDSCAPE_LAYOUT_2X2_GUEST_MOBILE_IMAGE: "landscape_layout2x2_guestMobileImage",

  PORTRAIT_LAYOUT_1X1_MAIN_IMAGE: "portrait_layout1x1_mainImage",
  PORTRAIT_LAYOUT_1X1_MOBILE_IMAGE: "portrait_layout1x1_mobileImage",
  PORTRAIT_LAYOUT_1X1_GUEST_MAIN_IMAGE: "portrait_layout1x1_guestMainImage",
  PORTRAIT_LAYOUT_1X1_GUEST_MOBILE_IMAGE: "portrait_layout1x1_guestMobileImage",
  PORTRAIT_LAYOUT_1X2_MAIN_IMAGE: "portrait_layout1x2_mainImage",
  PORTRAIT_LAYOUT_1X2_MOBILE_IMAGE: "portrait_layout1x2_mobileImage",
  PORTRAIT_LAYOUT_1X2_GUEST_MAIN_IMAGE: "portrait_layout1x2_guestMainImage",
  PORTRAIT_LAYOUT_1X2_GUEST_MOBILE_IMAGE: "portrait_layout1x2_guestMobileImage",
  PORTRAIT_LAYOUT_2X1_MAIN_IMAGE: "portrait_layout2x1_mainImage",
  PORTRAIT_LAYOUT_2X1_MOBILE_IMAGE: "portrait_layout2x1_mobileImage",
  PORTRAIT_LAYOUT_2X1_GUEST_MAIN_IMAGE: "portrait_layout2x1_guestMainImage",
  PORTRAIT_LAYOUT_2X1_GUEST_MOBILE_IMAGE: "portrait_layout2x1_guestMobileImage",
  PORTRAIT_LAYOUT_2X2_MAIN_IMAGE: "portrait_layout2x2_mainImage",
  PORTRAIT_LAYOUT_2X2_MOBILE_IMAGE: "portrait_layout2x2_mobileImage",
  PORTRAIT_LAYOUT_2X2_GUEST_MAIN_IMAGE: "portrait_layout2x2_guestMainImage",
  PORTRAIT_LAYOUT_2X2_GUEST_MOBILE_IMAGE: "portrait_layout2x2_guestMobileImage",

  SQUARE_LAYOUT_1X1_MAIN_IMAGE: "square_layout1x1_mainImage",
  SQUARE_LAYOUT_1X1_MOBILE_IMAGE: "square_layout1x1_mobileImage",
  SQUARE_LAYOUT_1X1_GUEST_MAIN_IMAGE: "square_layout1x1_guestMainImage",
  SQUARE_LAYOUT_1X1_GUEST_MOBILE_IMAGE: "square_layout1x1_guestMobileImage",
  SQUARE_LAYOUT_1X2_MAIN_IMAGE: "square_layout1x2_mainImage",
  SQUARE_LAYOUT_1X2_MOBILE_IMAGE: "square_layout1x2_mobileImage",
  SQUARE_LAYOUT_1X2_GUEST_MAIN_IMAGE: "square_layout1x2_guestMainImage",
  SQUARE_LAYOUT_1X2_GUEST_MOBILE_IMAGE: "square_layout1x2_guestMobileImage",
  SQUARE_LAYOUT_2X1_MAIN_IMAGE: "square_layout2x1_mainImage",
  SQUARE_LAYOUT_2X1_MOBILE_IMAGE: "square_layout2x1_mobileImage",
  SQUARE_LAYOUT_2X1_GUEST_MAIN_IMAGE: "square_layout2x1_guestMainImage",
  SQUARE_LAYOUT_2X1_GUEST_MOBILE_IMAGE: "square_layout2x1_guestMobileImage",
  SQUARE_LAYOUT_2X2_MAIN_IMAGE: "square_layout2x2_mainImage",
  SQUARE_LAYOUT_2X2_MOBILE_IMAGE: "square_layout2x2_mobileImage",
  SQUARE_LAYOUT_2X2_GUEST_MAIN_IMAGE: "square_layout2x2_guestMainImage",
  SQUARE_LAYOUT_2X2_GUEST_MOBILE_IMAGE: "square_layout2x2_guestMobileImage",
  
  // New tile status fields from Monday.com
  PORTRAIT_TILE_STATUS: "Portrait Tile",
  LANDSCAPE_TILE_STATUS: "Landscape tile",

  ARTICLE_ID: "articleId",
  MOBILE_ARTICLE_ID: "mobileArticleId",
  DESCRIPTION: "description",
  IS_GAME_NEW: "isGameAllen",
  IS_GAME_POPULAR: "isGamePopular",
  IS_GAME_HOT: "isGameHot",
  IS_GAME_EXCLUSIVE: "isGameExclusive",
  GAMELABELS_DROPS_AND_WINS: "gameLabelsData_Drops and Wins",
  GAMELABELS_RISING_STAR: "gameLabelsData_Rising Star",
  GAMELABELS_EXCLUSIVE: "gameLabelsData_Exclusive",
  GAMELABELS_NEW: "gameLabelsData_New",
  GAMESCUSTOMFIELDS_PROVIDER: "gamesCustomFields_provider",
  GAMESCUSTOMFIELDS_EXTERNALPROVIDERGAMEID: "gamesCustomFields_externalProviderGameId",
  GAMESCUSTOMFIELDS_GAMETYPE: "gamesCustomFields_gameType",
  GAMESCUSTOMFIELDS_THEME: "gamesCustomFields_theme",
  GAMESCUSTOMFIELDS_FEATURES: "gamesCustomFields_features",
  GAMESCUSTOMFIELDS_VOLATILITY: "gamesCustomFields_volatility",
  GAMESCUSTOMFIELDS_RTP: "gamesCustomFields_rtp",
  GAMESCUSTOMFIELDS_LINES: "gamesCustomFields_lines",
  GAMESCUSTOMFIELDS_REELS: "gamesCustomFields_reels",
} as const;

export const CORE_REQUIRED_INPUT_HEADER_KEYS: (keyof typeof INPUT_HEADER_MAPPINGS)[] = [
  'GAME_CODE',
  'NAME',
  'GAME_PROVIDER',
];

export const PLACEHOLDER_INFO_REQUIRED_COLUMNS = "Core required headers: IMS Game Code, Name, Game Provider.";

export const OUTPUT_CSV_COLUMNS: (keyof ProcessedGameData | 'gameLabelsData_Drops and Wins' | 'gameLabelsData_Rising Star')[] = [
  'gameCode',
  'name',
  'isActive',
  'mobileGameCode',
  'seoFriendlyGameName',
  'desktopGameType',
  'mobileGameType',
  'liveLaunchAlias',
  'bingoGameType',
  'vfGameType',
  'jackpotCode',
  'demoModeSupport',
  'gameMode',
  'gameProvider',
  'urlCustomParameters',
  'isExcludedFromPGG',
  'isExcludedFromSitemap',
  'deviceAvailability_mobile',
  'deviceAvailability_tablet',
  'deviceAvailability_desktop',
  'browserAvailability_edge',
  'browserAvailability_safari',
  'browserAvailability_chrome',
  'browserAvailability_firefox',
  'browserAvailability_other',
  'osAvailability_ios',
  'osAvailability_macintosh',
  'osAvailability_android',
  'osAvailability_windows',
  'osAvailability_other',
  'defaultGameImage',
  'landscape_layout1x1_mainImage',
  'landscape_layout1x1_mobileImage',
  'landscape_layout1x1_guestMainImage',
  'landscape_layout1x1_guestMobileImage',
  'landscape_layout1x2_mainImage',
  'landscape_layout1x2_mobileImage',
  'landscape_layout1x2_guestMainImage',
  'landscape_layout1x2_guestMobileImage',
  'landscape_layout2x1_mainImage',
  'landscape_layout2x1_mobileImage',
  'landscape_layout2x1_guestMainImage',
  'landscape_layout2x1_guestMobileImage',
  'landscape_layout2x2_mainImage',
  'landscape_layout2x2_mobileImage',
  'landscape_layout2x2_guestMainImage',
  'landscape_layout2x2_guestMobileImage',
  'square_layout1x1_mainImage',
  'square_layout1x1_mobileImage',
  'square_layout1x1_guestMainImage',
  'square_layout1x1_guestMobileImage',
  'square_layout1x2_mainImage',
  'square_layout1x2_mobileImage',
  'square_layout1x2_guestMainImage',
  'square_layout1x2_guestMobileImage',
  'square_layout2x1_mainImage',
  'square_layout2x1_mobileImage',
  'square_layout2x1_guestMainImage',
  'square_layout2x1_guestMobileImage',
  'square_layout2x2_mainImage',
  'square_layout2x2_mobileImage',
  'square_layout2x2_guestMainImage',
  'square_layout2x2_guestMobileImage',
  'portrait_layout1x1_mainImage',
  'portrait_layout1x1_mobileImage',
  'portrait_layout1x1_guestMainImage',
  'portrait_layout1x1_guestMobileImage',
  'portrait_layout1x2_mainImage',
  'portrait_layout1x2_mobileImage',
  'portrait_layout1x2_guestMainImage',
  'portrait_layout1x2_guestMobileImage',
  'portrait_layout2x1_mainImage',
  'portrait_layout2x1_mobileImage',
  'portrait_layout2x1_guestMainImage',
  'portrait_layout2x1_guestMobileImage',
  'portrait_layout2x2_mainImage',
  'portrait_layout2x2_mobileImage',
  'portrait_layout2x2_guestMainImage',
  'portrait_layout2x2_guestMobileImage',
  'articleId',
  'mobileArticleId',
  'description',
  'isGameNew',
  'isGamePopular',
  'isGameHot',
  'isGameExclusive',
  'gameLabelsData_Drops and Wins',
  'gameLabelsData_Rising Star',
  'gameLabelsData_Exclusive',
  'gameLabelsData_New',
  'gamesCustomFields_gameType',
  'gamesCustomFields_theme',
  'gamesCustomFields_features',
  'gamesCustomFields_volatility',
  'gamesCustomFields_rtp',
  'gamesCustomFields_lines',
  'gamesCustomFields_reels',
  'gamesCustomFields_provider',
  'gamesCustomFields_externalProviderGameId',
];